/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  customer_list: () => import("@/views/customer/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  inventory_list: () => import("@/views/inventory/list/index.vue"),
  "inventory_stock-in": () => import("@/views/inventory/stock-in/index.vue"),
  repair_item: () => import("@/views/repair/item/index.vue"),
  repair_list: () => import("@/views/repair/list/index.vue"),
  repair_material: () => import("@/views/repair/material/index.vue"),
  repair_record: () => import("@/views/repair/record/index.vue"),
  repair_settlement: () => import("@/views/repair/settlement/index.vue"),
  system_permission: () => import("@/views/system/permission/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_store: () => import("@/views/system/store/index.vue"),
  system_technician: () => import("@/views/system/technician/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  vehicle_list: () => import("@/views/vehicle/list/index.vue"),
};
