/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute, ElegantRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'customer',
    path: '/customer',
    component: 'layout.base',
    meta: {
      order: 2,
      requiresAuth: true,
      title: 'menu.customer',
      i18nKey: 'route.customer',
      i18nTitle: true,
      icon: 'material-symbols:person-outline'
    },
    children: [
      {
        name: 'customer_list',
        path: '/customer/list',
        component: 'view.customer_list',
        meta: {
          title: 'menu.customer.list',
          i18nKey: 'route.customer_list',
          i18nTitle: true,
          icon: 'material-symbols:group-outline',
          requiresAuth: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'material-symbols:dashboard-outline',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'inventory',
    path: '/inventory',
    component: 'layout.base',
    meta: {
      order: 3,
      requiresAuth: true,
      title: 'menu.inventory',
      i18nKey: 'route.inventory',
      i18nTitle: true,
      icon: 'material-symbols:inventory-2-outline'
    },
    children: [
      {
        name: 'inventory_list',
        path: '/inventory/list',
        component: 'view.inventory_list',
        meta: {
          title: 'menu.inventory.list',
          i18nKey: 'route.inventory_list',
          i18nTitle: true,
          icon: 'material-symbols:list-alt-outline',
          requiresAuth: true
        }
      },
      {
        name: 'inventory_stock-in',
        path: '/inventory/stock-in',
        component: 'view.inventory_stock-in',
        meta: {
          title: 'inventory_stock-in',
          i18nKey: 'route.inventory_stock_in'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'repair',
    path: '/repair',
    component: 'layout.base',
    meta: {
      title: 'repair',
      i18nKey: 'route.repair',
      icon: 'material-symbols:build-outline'
    },
    children: [
      {
        name: 'repair_item',
        path: '/repair/item',
        component: 'view.repair_item',
        meta: {
          title: 'repair_item',
          i18nKey: 'route.repair_item',
          icon: 'material-symbols:handyman-outline',
          order: 4
        }
      },
      {
        name: 'repair_list',
        path: '/repair/list',
        component: 'view.repair_list',
        meta: {
          title: 'repair_list',
          i18nKey: 'route.repair_list',
          icon: 'material-symbols:receipt-long-outline',
          order: 1
        }
      },
      {
        name: 'repair_material',
        path: '/repair/material',
        component: 'view.repair_material',
        meta: {
          title: 'repair_material',
          i18nKey: 'route.repair_material',
          icon: 'material-symbols:inventory-2-outline',
          order: 5
        }
      },
      {
        name: 'repair_record',
        path: '/repair/record',
        component: 'view.repair_record',
        meta: {
          title: 'repair_record',
          i18nKey: 'route.repair_record',
          icon: 'material-symbols:history',
          order: 3
        }
      },
      {
        name: 'repair_settlement',
        path: '/repair/settlement',
        component: 'view.repair_settlement',
        meta: {
          title: 'repair_settlement',
          i18nKey: 'route.repair_settlement',
          icon: 'material-symbols:payments-outline',
          order: 2
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      order: 5,
      requiresAuth: true,
      title: 'menu.system',
      i18nKey: 'route.system',
      i18nTitle: true,
      icon: 'material-symbols:settings-outline'
    },
    children: [
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          order: 4,
          title: 'system_permission',
          icon: 'material-symbols:admin-panel-settings',
          i18nKey: 'route.system_permission',
          i18nTitle: true,
          requiresAuth: true
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          order: 3,
          title: 'system.role.title',
          i18nKey: 'route.system_role',
          i18nTitle: true,
          icon: 'material-symbols:shield-person-outline',
          requiresAuth: true
        }
      },
      {
        name: 'system_store',
        path: '/system/store',
        component: 'view.system_store',
        meta: {
          order: 1,
          title: 'menu.system.store',
          i18nKey: 'route.system_store',
          i18nTitle: true,
          icon: 'material-symbols:store-outline',
          requiresAuth: true
        }
      },
      {
        name: 'system_technician',
        path: '/system/technician',
        component: 'view.system_technician',
        meta: {
          order: 5,
          title: 'system_technician',
          i18nKey: 'route.system_technician',
          i18nTitle: true,
          icon: 'material-symbols:engineering-outline'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          order: 2,
          title: 'system.user.title',
          i18nKey: 'route.system_user',
          i18nTitle: true,
          icon: 'material-symbols:person-outline',
          requiresAuth: true
        }
      }
    ]
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    component: 'layout.base',
    meta: {
      order: 3,
      requiresAuth: true,
      title: 'menu.vehicle',
      i18nKey: 'route.vehicle',
      i18nTitle: true,
      icon: 'material-symbols:directions-car'
    },
    children: [
      {
        name: 'vehicle_list',
        path: '/vehicle/list',
        component: 'view.vehicle_list',
        meta: {
          title: 'menu.vehicle.list',
          i18nKey: 'route.vehicle_list',
          i18nTitle: true,
          icon: 'material-symbols:directions-car-outline',
          requiresAuth: true
        }
      }
    ]
  }
];
