/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute, ElegantRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'customer',
    path: '/customer',
    component: 'layout.base',
    meta: {
      order: 2,
      requiresAuth: true,
      title: 'menu.customer',
      i18nKey: 'route.customer',
      i18nTitle: true,
      icon: 'material-symbols:person-outline'
    },
    children: [
      {
        name: 'customer_list',
        path: '/customer/list',
        component: 'view.customer_list',
        meta: {
          title: 'menu.customer.list',
          i18nKey: 'route.customer_list',
          i18nTitle: true,
          icon: 'material-symbols:group-outline',
          requiresAuth: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'material-symbols:dashboard-outline',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'repair-order',
    path: '/repair-order',
    component: 'layout.base',
    meta: {
      title: 'repair-order',
      i18nKey: 'route.repair-order',
      order: 4,
      icon: 'material-symbols:build-outline'
    },
    children: [
      {
        name: 'repair-order_list',
        path: '/repair-order/list',
        component: 'view.repair-order_list',
        meta: {
          title: 'repair-order_list',
          i18nKey: 'route.repair-order_list',
          icon: 'material-symbols:build'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      order: 5,
      requiresAuth: true,
      title: 'menu.system',
      i18nKey: 'route.system',
      i18nTitle: true,
      icon: 'material-symbols:settings-outline'
    },
    children: [
      {
        name: 'system_store',
        path: '/system/store',
        component: 'view.system_store',
        meta: {
          title: 'menu.system.store',
          i18nKey: 'route.system_store',
          i18nTitle: true,
          icon: 'material-symbols:store-outline',
          requiresAuth: true
        }
      },
      {
        name: 'system_permission',
        path: '/system/permission',
        component: 'view.system_permission',
        meta: {
          title: 'system_permission',
          icon: 'material-symbols:admin-panel-settings',
          i18nKey: 'route.system_permission'
        }
      },
    ]
  },
  {
    name: 'vehicle',
    path: '/vehicle',
    component: 'layout.base',
    meta: {
      order: 3,
      requiresAuth: true,
      title: 'menu.vehicle',
      i18nKey: 'route.vehicle',
      i18nTitle: true,
      icon: 'material-symbols:directions-car'
    },
    children: [
      {
        name: 'vehicle_list',
        path: '/vehicle/list',
        component: 'view.vehicle_list',
        meta: {
          title: 'menu.vehicle.list',
          i18nKey: 'route.vehicle_list',
          i18nTitle: true,
          icon: 'material-symbols:directions-car-outline',
          requiresAuth: true
        }
      }
    ]
  }
];
